ALTER TYPE "ColorTheme" ADD VALUE 'SYPHER_LIGHT';
ALTER TYPE "ColorTheme" ADD VALUE 'CREXTIO_WARM';
ALTER TYPE "ColorTheme" ADD VALUE 'SBB_INDUSTRIAL';
ALTER TYPE "ColorTheme" ADD VALUE 'WELLNESS_TEAL';
