ALTER TYPE "AgreementStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "AgreementStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "AgreementStatus" ADD VALUE IF NOT EXISTS 'SUSPENDED';

CREATE TYPE "RentDueWeek" AS ENUM ('FIRST', 'SECOND', 'THIRD', 'FOURTH', 'LAST');
CREATE TYPE "RentDueWeekday" AS ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY');
CREATE TYPE "AgreementPrepaymentKind" AS ENUM ('SECURITY_DEPOSIT', 'FIRST_RENT');
CREATE TYPE "AgreementPrepaymentTransactionType" AS ENUM ('COLLECTION', 'REFUND', 'DEDUCTION', 'RETENTION', 'APPLICATION');
